In [7]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
print("original array:",arr)
x=np.where(arr==4)
print("\n indexes where the values is 4:\n",x)


original array: [1 2 3 4 5 4 4]

 indexes where the values is 4:
 (array([3, 5, 6]),)


In [8]:
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print("original array:",arr)
print("\n indexes where the values are even:",x)

original array: [1 2 3 4 5 6 7 8]

 indexes where the values are even: (array([1, 3, 5, 7]),)


In [9]:

x=np.searchsorted(arr,3,side='left')
print("\nindexes where the value 3 should be inserted,starting from the right:",x)


indexes where the value 3 should be inserted,starting from the right: 2


In [10]:

arr=np.array([3,2,0,1])
print("\noriginal array:",arr)
print("\nsorted array:",np.sort(arr))
arr=np.array([[3,2,4],[5,0,1]])
print("\noriginal array:",arr)
print("\nsorted array:",np.sort(arr))



original array: [3 2 0 1]

sorted array: [0 1 2 3]

original array: [[3 2 4]
 [5 0 1]]

sorted array: [[2 3 4]
 [0 1 5]]


In [11]:
arr=np.array([41,42,43,44])
filter_arr=arr>42
newarr=arr[filter_arr]
print("\noriginal array:",arr)
print("\nfilter array:condition->42:",filter_arr)
print("\nnew array:",newarr)



original array: [41 42 43 44]

filter array:condition->42: [False False  True  True]

new array: [43 44]
